[package]
name = "runix_terminal"
version = "0.1.0"
description = "Runix Terminal Desktop Client"
authors = ["Runix Infrastructure <support@runix.in>"]
edition = "2024"
rust-version = "1.90"

[lib]
name = "runix_terminal_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1" }
tauri-plugin-log = "2"
