/**
 * RUNIX UNIVERSAL FILE INTELLIGENCE & LANGUAGE REGISTRY
 * 
 * Central authoritative registry defining language identification,
 * editor modes, MIME types, and intrinsic capabilities for all supported environments.
 * 
 * Strict architectural rule:
 * NO per-language UI conditions (if python => showRun).
 * All capabilities MUST be resolved from this central source of truth.
 */

export interface LanguageDefinition {
  languageId: string;
  displayName: string;
  extensions: string[];
  filenames: string[];
  mimeTypes: string[];
  type: 'compiled' | 'interpreted' | 'hybrid' | 'markup' | 'data' | 'config' | 'document' | 'shell';
  runtimeId?: string;
  editorLanguage: string;
  buildCapability: boolean;
  runCapability: boolean;
  debugCapability: boolean;
  testCapability: boolean;
  stdinCapability: boolean;
  stdoutCapability: boolean;
  stderrCapability: boolean;
  multiFileCapability: boolean;
  packageCapability: boolean;
  networkCapability: boolean;
  frameworkCapability: boolean;
  databaseCapability: boolean;
  defaultBuildCommand?: string;
  defaultRunCommand?: string;
  defaultTestCommand?: string;
  defaultDebugCommand?: string;
  supportedOS: string[];
  supportedArchitectures: string[];
  runtimeRequirements: string;
  isSpecialManifest?: boolean;
  category: 'code' | 'config' | 'markup' | 'data' | 'document' | 'binary';
}

export const RUNIX_LANGUAGE_REGISTRY: Record<string, LanguageDefinition> = {
  // === INTERPRETED LANGUAGES ===
  python: {
    languageId: 'python',
    displayName: 'Python',
    extensions: ['.py', '.pyw', '.pyi'],
    filenames: [],
    mimeTypes: ['text/x-python', 'application/x-python-code'],
    type: 'interpreted',
    runtimeId: 'python',
    editorLanguage: 'python',
    buildCapability: false,
    runCapability: true,
    debugCapability: true,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultRunCommand: 'python "{file}"',
    defaultTestCommand: 'pytest',
    defaultDebugCommand: 'python -m pdb "{file}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Python 3.8+',
    category: 'code',
  },

  lua: {
    languageId: 'lua',
    displayName: 'Lua',
    extensions: ['.lua'],
    filenames: [],
    mimeTypes: ['text/x-lua', 'application/x-lua'],
    type: 'interpreted',
    runtimeId: 'lua',
    editorLanguage: 'lua',
    buildCapability: false,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultRunCommand: 'lua "{file}"',
    defaultTestCommand: 'lua -e "require(\'tests\')"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Lua 5.1+ / LuaJIT',
    category: 'code',
  },

  javascript: {
    languageId: 'javascript',
    displayName: 'JavaScript',
    extensions: ['.js', '.mjs', '.cjs'],
    filenames: [],
    mimeTypes: ['text/javascript', 'application/javascript'],
    type: 'interpreted',
    runtimeId: 'nodejs',
    editorLanguage: 'javascript',
    buildCapability: false,
    runCapability: true,
    debugCapability: true,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultRunCommand: 'node "{file}"',
    defaultTestCommand: 'npm test',
    defaultDebugCommand: 'node --inspect "{file}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Node.js 18+',
    category: 'code',
  },

  typescript: {
    languageId: 'typescript',
    displayName: 'TypeScript',
    extensions: ['.ts', '.mts', '.cts'],
    filenames: [],
    mimeTypes: ['text/typescript', 'application/typescript'],
    type: 'hybrid',
    runtimeId: 'typescript',
    editorLanguage: 'typescript',
    buildCapability: true,
    runCapability: true,
    debugCapability: true,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultBuildCommand: 'npx tsc --noEmit',
    defaultRunCommand: 'npx tsx "{file}"',
    defaultTestCommand: 'npm test',
    defaultDebugCommand: 'node --inspect -r ts-node/register "{file}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Node.js with TypeScript / tsx runner',
    category: 'code',
  },

  typescriptreact: {
    languageId: 'typescriptreact',
    displayName: 'TypeScript React (TSX)',
    extensions: ['.tsx'],
    filenames: [],
    mimeTypes: ['text/typescript-jsx'],
    type: 'hybrid',
    runtimeId: 'react',
    editorLanguage: 'typescript',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: false,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultBuildCommand: 'npx tsc --noEmit',
    defaultRunCommand: 'npx tsx "{file}"',
    defaultTestCommand: 'npm test',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'React ecosystem tooling (Vite / Next.js)',
    category: 'code',
  },

  javascriptreact: {
    languageId: 'javascriptreact',
    displayName: 'JavaScript React (JSX)',
    extensions: ['.jsx'],
    filenames: [],
    mimeTypes: ['text/jsx'],
    type: 'hybrid',
    runtimeId: 'react',
    editorLanguage: 'javascript',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: false,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultBuildCommand: 'npx tsc --noEmit',
    defaultRunCommand: 'npx tsx "{file}"',
    defaultTestCommand: 'npm test',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'React ecosystem tooling',
    category: 'code',
  },

  vue: {
    languageId: 'vue',
    displayName: 'Vue',
    extensions: ['.vue'],
    filenames: [],
    mimeTypes: ['text/x-vue'],
    type: 'hybrid',
    runtimeId: 'vue',
    editorLanguage: 'vue',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: false,
    stdinCapability: false,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultBuildCommand: 'npm run build',
    defaultRunCommand: 'npm run dev',
    supportedOS: ['all'],
    supportedArchitectures: ['all'],
    runtimeRequirements: 'Node.js / Vite / Vue CLI',
    category: 'code',
  },

  awk: {
    languageId: 'awk',
    displayName: 'AWK',
    extensions: ['.awk'],
    filenames: [],
    mimeTypes: ['text/x-awk'],
    type: 'interpreted',
    runtimeId: 'awk',
    editorLanguage: 'awk',
    buildCapability: false,
    runCapability: true,
    debugCapability: false,
    testCapability: false,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: false,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    defaultRunCommand: 'awk -f "{file}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'GNU Awk / POSIX awk',
    category: 'code',
  },

  ruby: {
    languageId: 'ruby',
    displayName: 'Ruby',
    extensions: ['.rb', '.rake'],
    filenames: ['Gemfile', 'Rakefile'],
    mimeTypes: ['text/x-ruby', 'application/x-ruby'],
    type: 'interpreted',
    runtimeId: 'ruby',
    editorLanguage: 'ruby',
    buildCapability: false,
    runCapability: true,
    debugCapability: true,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultRunCommand: 'ruby "{file}"',
    defaultTestCommand: 'rake test',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Ruby 3.0+',
    category: 'code',
  },

  php: {
    languageId: 'php',
    displayName: 'PHP',
    extensions: ['.php', '.phtml'],
    filenames: ['composer.json'],
    mimeTypes: ['text/x-php', 'application/x-php'],
    type: 'interpreted',
    runtimeId: 'php',
    editorLanguage: 'php',
    buildCapability: false,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultRunCommand: 'php "{file}"',
    defaultTestCommand: 'phpunit',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'PHP 8.0+ CLI',
    category: 'code',
  },

  perl: {
    languageId: 'perl',
    displayName: 'Perl',
    extensions: ['.pl', '.pm'],
    filenames: [],
    mimeTypes: ['text/x-perl'],
    type: 'interpreted',
    runtimeId: 'perl',
    editorLanguage: 'perl',
    buildCapability: false,
    runCapability: true,
    debugCapability: false,
    testCapability: false,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultRunCommand: 'perl "{file}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Perl 5.x',
    category: 'code',
  },

  // === COMPILED / SYSTEMS LANGUAGES ===
  c: {
    languageId: 'c',
    displayName: 'C',
    extensions: ['.c', '.h'],
    filenames: [],
    mimeTypes: ['text/x-c', 'text/x-chdr'],
    type: 'compiled',
    runtimeId: 'c',
    editorLanguage: 'c',
    buildCapability: true,
    runCapability: true,
    debugCapability: true,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: false,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'gcc -O2 -Wall "{file}" -o "{output}"',
    defaultRunCommand: '"{output}"',
    defaultTestCommand: 'make test',
    defaultDebugCommand: 'gdb "{output}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'GCC / Clang / MSVC',
    category: 'code',
  },

  cpp: {
    languageId: 'cpp',
    displayName: 'C++',
    extensions: ['.cpp', '.cc', '.cxx', '.hpp', '.hxx', '.hh'],
    filenames: [],
    mimeTypes: ['text/x-c++src', 'text/x-c++hdr'],
    type: 'compiled',
    runtimeId: 'cpp',
    editorLanguage: 'cpp',
    buildCapability: true,
    runCapability: true,
    debugCapability: true,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: false,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'g++ -O2 -std=c++17 -Wall "{file}" -o "{output}"',
    defaultRunCommand: '"{output}"',
    defaultTestCommand: 'make test',
    defaultDebugCommand: 'gdb "{output}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'G++ / Clang++ / MSVC',
    category: 'code',
  },

  rust: {
    languageId: 'rust',
    displayName: 'Rust',
    extensions: ['.rs'],
    filenames: [],
    mimeTypes: ['text/rust'],
    type: 'compiled',
    runtimeId: 'rust',
    editorLanguage: 'rust',
    buildCapability: true,
    runCapability: true,
    debugCapability: true,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'cargo build',
    defaultRunCommand: 'cargo run',
    defaultTestCommand: 'cargo test',
    defaultDebugCommand: 'rust-gdb "{output}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Rustc + Cargo',
    category: 'code',
  },

  go: {
    languageId: 'go',
    displayName: 'Go',
    extensions: ['.go'],
    filenames: ['go.mod', 'go.sum'],
    mimeTypes: ['text/x-go'],
    type: 'compiled',
    runtimeId: 'go',
    editorLanguage: 'go',
    buildCapability: true,
    runCapability: true,
    debugCapability: true,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultBuildCommand: 'go build -o "{output}" "{file}"',
    defaultRunCommand: 'go run "{file}"',
    defaultTestCommand: 'go test ./...',
    defaultDebugCommand: 'dlv debug "{file}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Go 1.20+',
    category: 'code',
  },

  java: {
    languageId: 'java',
    displayName: 'Java',
    extensions: ['.java', '.class', '.jar'],
    filenames: ['pom.xml', 'build.gradle', 'build.gradle.kts'],
    mimeTypes: ['text/x-java-source', 'application/java-archive'],
    type: 'compiled',
    runtimeId: 'java',
    editorLanguage: 'java',
    buildCapability: true,
    runCapability: true,
    debugCapability: true,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultBuildCommand: 'javac "{file}"',
    defaultRunCommand: 'java "{file}"',
    defaultTestCommand: 'mvn test',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'OpenJDK / JDK 17+',
    category: 'code',
  },

  kotlin: {
    languageId: 'kotlin',
    displayName: 'Kotlin',
    extensions: ['.kt', '.kts'],
    filenames: ['build.gradle.kts'],
    mimeTypes: ['text/x-kotlin'],
    type: 'compiled',
    runtimeId: 'kotlin',
    editorLanguage: 'kotlin',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'kotlinc "{file}" -include-runtime -d "{output}.jar"',
    defaultRunCommand: 'java -jar "{output}.jar"',
    defaultTestCommand: 'gradle test',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Kotlin compiler / JDK',
    category: 'code',
  },

  csharp: {
    languageId: 'csharp',
    displayName: 'C#',
    extensions: ['.cs'],
    filenames: [],
    mimeTypes: ['text/x-csharp'],
    type: 'compiled',
    runtimeId: 'csharp',
    editorLanguage: 'csharp',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultBuildCommand: 'dotnet build',
    defaultRunCommand: 'dotnet run',
    defaultTestCommand: 'dotnet test',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: '.NET SDK 8.0+',
    category: 'code',
  },

  swift: {
    languageId: 'swift',
    displayName: 'Swift',
    extensions: ['.swift'],
    filenames: ['Package.swift'],
    mimeTypes: ['text/x-swift'],
    type: 'compiled',
    runtimeId: 'swift',
    editorLanguage: 'swift',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'swiftc "{file}" -o "{output}"',
    defaultRunCommand: 'swift run',
    defaultTestCommand: 'swift test',
    supportedOS: ['darwin', 'linux'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Swift toolchain',
    category: 'code',
  },

  dart: {
    languageId: 'dart',
    displayName: 'Dart',
    extensions: ['.dart'],
    filenames: ['pubspec.yaml', 'pubspec.lock'],
    mimeTypes: ['application/dart'],
    type: 'hybrid',
    runtimeId: 'dart',
    editorLanguage: 'dart',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultRunCommand: 'dart run "{file}"',
    defaultTestCommand: 'dart test',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Dart SDK',
    category: 'code',
  },

  zig: {
    languageId: 'zig',
    displayName: 'Zig',
    extensions: ['.zig'],
    filenames: ['build.zig'],
    mimeTypes: ['text/x-zig'],
    type: 'compiled',
    runtimeId: 'zig',
    editorLanguage: 'zig',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: false,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'zig build-exe "{file}"',
    defaultRunCommand: 'zig run "{file}"',
    defaultTestCommand: 'zig test "{file}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Zig compiler 0.11+',
    category: 'code',
  },

  elixir: {
    languageId: 'elixir',
    displayName: 'Elixir',
    extensions: ['.ex', '.exs'],
    filenames: ['mix.exs'],
    mimeTypes: ['text/x-elixir'],
    type: 'hybrid',
    runtimeId: 'elixir',
    editorLanguage: 'elixir',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: true,
    databaseCapability: false,
    defaultRunCommand: 'elixir "{file}"',
    defaultTestCommand: 'mix test',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Erlang/OTP + Elixir',
    category: 'code',
  },

  erlang: {
    languageId: 'erlang',
    displayName: 'Erlang',
    extensions: ['.erl', '.hrl'],
    filenames: ['rebar.config'],
    mimeTypes: ['text/x-erlang'],
    type: 'compiled',
    runtimeId: 'erlang',
    editorLanguage: 'erlang',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: true,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'erlc "{file}"',
    defaultRunCommand: 'escript "{file}"',
    defaultTestCommand: 'rebar3 eunit',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Erlang/OTP',
    category: 'code',
  },

  fortran: {
    languageId: 'fortran',
    displayName: 'Fortran',
    extensions: ['.f90', '.f95', '.f03', '.f', '.for'],
    filenames: [],
    mimeTypes: ['text/x-fortran'],
    type: 'compiled',
    runtimeId: 'fortran',
    editorLanguage: 'fortran',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: false,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'gfortran "{file}" -o "{output}"',
    defaultRunCommand: '"{output}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'GFortran',
    category: 'code',
  },

  verilog: {
    languageId: 'verilog',
    displayName: 'Verilog',
    extensions: ['.v', '.vh', '.sv'],
    filenames: [],
    mimeTypes: ['text/x-verilog'],
    type: 'compiled',
    runtimeId: 'verilog',
    editorLanguage: 'verilog',
    buildCapability: true,
    runCapability: true,
    debugCapability: false,
    testCapability: true,
    stdinCapability: false,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'iverilog -o "{output}" "{file}"',
    defaultRunCommand: 'vvp "{output}"',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Icarus Verilog',
    category: 'code',
  },

  // === SHELLS & SCRIPTS ===
  shell: {
    languageId: 'shell',
    displayName: 'Bash / Shell',
    extensions: ['.sh', '.bash', '.zsh'],
    filenames: [],
    mimeTypes: ['application/x-sh', 'text/x-shellscript'],
    type: 'shell',
    runtimeId: 'bash',
    editorLanguage: 'shell',
    buildCapability: false,
    runCapability: true,
    debugCapability: false,
    testCapability: false,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: false,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultRunCommand: 'bash "{file}"',
    supportedOS: ['linux', 'darwin', 'windows'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'GNU Bash',
    category: 'code',
  },

  powershell: {
    languageId: 'powershell',
    displayName: 'PowerShell',
    extensions: ['.ps1', '.psm1', '.psd1'],
    filenames: [],
    mimeTypes: ['text/x-powershell'],
    type: 'shell',
    runtimeId: 'powershell',
    editorLanguage: 'powershell',
    buildCapability: false,
    runCapability: true,
    debugCapability: false,
    testCapability: false,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: false,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultRunCommand: 'powershell -ExecutionPolicy Bypass -File "{file}"',
    supportedOS: ['windows', 'linux', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'PowerShell Core / Windows PowerShell',
    category: 'code',
  },

  // === CONFIG & MANIFESTS (Special & Extension) ===
  dockerfile: {
    languageId: 'dockerfile',
    displayName: 'Dockerfile',
    extensions: ['.dockerfile'],
    filenames: ['dockerfile', 'dockerfile.dev', 'dockerfile.prod'],
    mimeTypes: ['text/x-dockerfile'],
    type: 'config',
    runtimeId: 'docker',
    editorLanguage: 'dockerfile',
    buildCapability: true,
    runCapability: false,
    debugCapability: false,
    testCapability: false,
    stdinCapability: false,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: false,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'docker build -t app .',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'Docker Engine',
    isSpecialManifest: true,
    category: 'config',
  },

  makefile: {
    languageId: 'makefile',
    displayName: 'Makefile',
    extensions: ['.mk'],
    filenames: ['makefile', 'gnumakefile'],
    mimeTypes: ['text/x-makefile'],
    type: 'config',
    runtimeId: 'make',
    editorLanguage: 'makefile',
    buildCapability: true,
    runCapability: false,
    debugCapability: false,
    testCapability: true,
    stdinCapability: false,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'make',
    defaultTestCommand: 'make test',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'GNU Make',
    isSpecialManifest: true,
    category: 'config',
  },

  cmake: {
    languageId: 'cmake',
    displayName: 'CMake',
    extensions: ['.cmake'],
    filenames: ['cmakelists.txt'],
    mimeTypes: ['text/x-cmake'],
    type: 'config',
    runtimeId: 'cmake',
    editorLanguage: 'cmake',
    buildCapability: true,
    runCapability: false,
    debugCapability: false,
    testCapability: true,
    stdinCapability: false,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    defaultBuildCommand: 'cmake -B build && cmake --build build',
    supportedOS: ['linux', 'windows', 'darwin'],
    supportedArchitectures: ['x64', 'arm64'],
    runtimeRequirements: 'CMake 3.20+',
    isSpecialManifest: true,
    category: 'config',
  },

  // === DATA & MARKUP (Non-runnable directly) ===
  markdown: {
    languageId: 'markdown',
    displayName: 'Markdown',
    extensions: ['.md', '.markdown', '.mdown', '.mkdn'],
    filenames: ['readme.md', 'changelog.md', 'license.md'],
    mimeTypes: ['text/markdown'],
    type: 'document',
    editorLanguage: 'markdown',
    buildCapability: false,
    runCapability: false,
    debugCapability: false,
    testCapability: false,
    stdinCapability: false,
    stdoutCapability: false,
    stderrCapability: false,
    multiFileCapability: false,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    supportedOS: ['all'],
    supportedArchitectures: ['all'],
    runtimeRequirements: 'Document viewer',
    category: 'document',
  },

  json: {
    languageId: 'json',
    displayName: 'JSON',
    extensions: ['.json', '.jsonc'],
    filenames: ['package.json', 'package-lock.json', 'tsconfig.json', 'runix.json', 'composer.json'],
    mimeTypes: ['application/json'],
    type: 'config',
    editorLanguage: 'json',
    buildCapability: false,
    runCapability: false,
    debugCapability: false,
    testCapability: false,
    stdinCapability: false,
    stdoutCapability: false,
    stderrCapability: false,
    multiFileCapability: false,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    supportedOS: ['all'],
    supportedArchitectures: ['all'],
    runtimeRequirements: 'JSON Parser',
    isSpecialManifest: true,
    category: 'config',
  },

  yaml: {
    languageId: 'yaml',
    displayName: 'YAML',
    extensions: ['.yaml', '.yml'],
    filenames: ['pubspec.yaml', 'docker-compose.yml', '.gitlab-ci.yml'],
    mimeTypes: ['text/yaml', 'application/x-yaml'],
    type: 'config',
    editorLanguage: 'yaml',
    buildCapability: false,
    runCapability: false,
    debugCapability: false,
    testCapability: false,
    stdinCapability: false,
    stdoutCapability: false,
    stderrCapability: false,
    multiFileCapability: false,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    supportedOS: ['all'],
    supportedArchitectures: ['all'],
    runtimeRequirements: 'YAML Parser',
    isSpecialManifest: true,
    category: 'config',
  },

  toml: {
    languageId: 'toml',
    displayName: 'TOML',
    extensions: ['.toml'],
    filenames: ['cargo.toml', 'pyproject.toml', 'pipfile'],
    mimeTypes: ['text/toml', 'application/toml'],
    type: 'config',
    editorLanguage: 'toml',
    buildCapability: false,
    runCapability: false,
    debugCapability: false,
    testCapability: false,
    stdinCapability: false,
    stdoutCapability: false,
    stderrCapability: false,
    multiFileCapability: false,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    supportedOS: ['all'],
    supportedArchitectures: ['all'],
    runtimeRequirements: 'TOML Parser',
    isSpecialManifest: true,
    category: 'config',
  },

  html: {
    languageId: 'html',
    displayName: 'HTML',
    extensions: ['.html', '.htm'],
    filenames: ['index.html'],
    mimeTypes: ['text/html'],
    type: 'markup',
    editorLanguage: 'html',
    buildCapability: false,
    runCapability: false,
    debugCapability: false,
    testCapability: false,
    stdinCapability: false,
    stdoutCapability: false,
    stderrCapability: false,
    multiFileCapability: false,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    supportedOS: ['all'],
    supportedArchitectures: ['all'],
    runtimeRequirements: 'Web browser',
    category: 'markup',
  },

  css: {
    languageId: 'css',
    displayName: 'CSS',
    extensions: ['.css'],
    filenames: [],
    mimeTypes: ['text/css'],
    type: 'markup',
    editorLanguage: 'css',
    buildCapability: false,
    runCapability: false,
    debugCapability: false,
    testCapability: false,
    stdinCapability: false,
    stdoutCapability: false,
    stderrCapability: false,
    multiFileCapability: false,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    supportedOS: ['all'],
    supportedArchitectures: ['all'],
    runtimeRequirements: 'Web browser / PostCSS',
    category: 'markup',
  },

  sql: {
    languageId: 'sql',
    displayName: 'SQL',
    extensions: ['.sql', '.sqlite', '.db'],
    filenames: ['schema.sql'],
    mimeTypes: ['application/sql', 'text/x-sql'],
    type: 'data',
    runtimeId: 'sql',
    editorLanguage: 'sql',
    buildCapability: false,
    runCapability: true,
    debugCapability: false,
    testCapability: false,
    stdinCapability: true,
    stdoutCapability: true,
    stderrCapability: true,
    multiFileCapability: true,
    packageCapability: false,
    networkCapability: true,
    frameworkCapability: false,
    databaseCapability: true,
    defaultRunCommand: 'python -c "import sqlite3,sys;c=sqlite3.connect(\':memory:\');cur=c.cursor();rows=[r for s in open(sys.argv[1],encoding=\'utf-8\').read().split(\';\') if s.strip() for r in cur.execute(s.strip()).fetchall()]; [print(r) for r in rows] if rows else print(\'Query executed successfully.\')" "{file}"',
    supportedOS: ['all'],
    supportedArchitectures: ['all'],
    runtimeRequirements: 'SQLite 3 (via Python/Host)',
    category: 'code',
  },

  plaintext: {
    languageId: 'plaintext',
    displayName: 'Plain Text',
    extensions: ['.txt', '.log'],
    filenames: [],
    mimeTypes: ['text/plain'],
    type: 'document',
    editorLanguage: 'plaintext',
    buildCapability: false,
    runCapability: false,
    debugCapability: false,
    testCapability: false,
    stdinCapability: false,
    stdoutCapability: false,
    stderrCapability: false,
    multiFileCapability: false,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    supportedOS: ['all'],
    supportedArchitectures: ['all'],
    runtimeRequirements: 'None',
    category: 'document',
  },
};

/**
 * Universal lookup: maps any filename (extension or manifest) to a canonical LanguageDefinition.
 */
export function identifyLanguage(filename: string): LanguageDefinition {
  if (!filename) return RUNIX_LANGUAGE_REGISTRY['plaintext'];

  const normalized = filename.trim().toLowerCase();
  const base = normalized.split(/[/\\]/).pop() || normalized;
  const ext = base.includes('.') ? `.${base.split('.').pop()}` : '';

  // 1. Exact manifest check first (case-insensitive)
  for (const def of Object.values(RUNIX_LANGUAGE_REGISTRY)) {
    if (def.filenames.some((fn) => fn.toLowerCase() === base)) {
      return def;
    }
  }

  // 2. Extension check
  if (ext) {
    for (const def of Object.values(RUNIX_LANGUAGE_REGISTRY)) {
      if (def.extensions.some((e) => e.toLowerCase() === ext)) {
        return def;
      }
    }
  }

  // 3. Fallback: Unknown
  return {
    languageId: 'unknown',
    displayName: 'Unknown',
    extensions: ext ? [ext] : [],
    filenames: [],
    mimeTypes: ['application/octet-stream'],
    type: 'document',
    editorLanguage: 'plaintext',
    buildCapability: false,
    runCapability: false,
    debugCapability: false,
    testCapability: false,
    stdinCapability: false,
    stdoutCapability: false,
    stderrCapability: false,
    multiFileCapability: false,
    packageCapability: false,
    networkCapability: false,
    frameworkCapability: false,
    databaseCapability: false,
    supportedOS: ['all'],
    supportedArchitectures: ['all'],
    runtimeRequirements: 'Unregistered file format',
    category: 'document',
  };
}
